from setuptools import setup, find_packages

setup(
    name='llmtoolz',
    version='0.1.0',
    description='AI toolbelt for the LLM model.',
    author='Martin Weiss & Nasim Rahaman',
    author_email='tbd',
    url='tbd',
    packages=find_packages(),
    install_requires=[
        'requests',
        'numpy>=1.18.5',
        'pandas',
        'goose3',
        'apify_client',
        'backoff',
        'diskcache',
        'openai',
        'openai_functions',
        'gitpython',
        'PyMuPDF',
        'tiktoken',
        'packaging',
        'scipy',
        'gnews',
        'rocketreach',
        'loguru',
        'google-auth',
        'python-docx',
	    'google-auth-oauthlib',
        'google-auth-httplib2',
        'google-api-python-client==2.107.0',
        'email_reply_parser',
        'PyPDF2',
        'pyvirtualdisplay',
        'webdriver-manager',
        'markdown',
        'pdfkit',
        'rich',
        'pydantic==2.0.3',
        'PyYAML',
        'celery==5.3.6',
        'scikit-learn',
        'fuzzysearch',
        'redis==5.0.1',
        'faiss-cpu==1.7.4',
        'thefuzz',
        'python-docx',
        'urlextract',
        'mistune',
        # Website stuff
        'Flask',
        'flask_wtf',
        'email_validator==1.1.3',
        'Flask-SQLAlchemy',
        'Flask-Migrate',
        'flask-login',
        'psycopg2-binary==2.9.5',
        'Flask-Admin',
        'Flask-Bootstrap',
        'Flask-Moment',
        'Flask-Uploads',
        'Flask-Bcrypt',
        'Flask-Testing',
        'Flask-Mail',
        'stripe',
        'gitpython',
        'openai',
        'fastapi',
        'uvicorn',
        'loguru',
        'pyjwt',
        'python-multipart',
        'stripe==7.9.0',
        'APScheduler',
        'alembic',
        'flask-cors',
        'flask-socketio',
        'watchdog',
        'simplegmail',
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers, Executives, Elected Officials, Children',
        'Programming Language :: Python :: 3.10',
    ],
)
